import type { ActivityEntry, Member, Project, Task } from './types';

export const MEMBERS: Member[] = [
  {
    id: 'u1',
    name: 'Ahmad Razif',
    email: 'ahmad.razif@pandaworks.com',
    role: 'Engineering Lead',
    department: 'Engineering',
    timezone: 'Asia/Kuala_Lumpur',
    avatarColor: 'oklch(0.62 0.18 260)',
  },
  {
    id: 'u2',
    name: 'Siti Aminah',
    email: 'siti.aminah@pandaworks.com',
    role: 'Product Manager',
    department: 'Product',
    timezone: 'Asia/Kuala_Lumpur',
    avatarColor: 'oklch(0.65 0.18 320)',
  },
  {
    id: 'u3',
    name: 'Lee Wei Ming',
    email: 'weiming.lee@pandaworks.com',
    role: 'Senior Engineer',
    department: 'Engineering',
    timezone: 'Asia/Singapore',
    avatarColor: 'oklch(0.68 0.15 190)',
  },
  {
    id: 'u4',
    name: 'Nurul Izzah',
    email: 'nurul.izzah@pandaworks.com',
    role: 'UX Designer',
    department: 'Design',
    timezone: 'Asia/Kuala_Lumpur',
    avatarColor: 'oklch(0.7 0.16 30)',
  },
  {
    id: 'u5',
    name: 'Raj Kumar',
    email: 'raj.kumar@pandaworks.com',
    role: 'Ops Manager',
    department: 'Operations',
    timezone: 'Asia/Jakarta',
    avatarColor: 'oklch(0.68 0.16 140)',
  },
  {
    id: 'u6',
    name: 'Mei Ling Tan',
    email: 'meiling.tan@pandaworks.com',
    role: 'Marketing Lead',
    department: 'Marketing',
    timezone: 'Asia/Singapore',
    avatarColor: 'oklch(0.7 0.15 0)',
  },
  {
    id: 'u7',
    name: 'David Chen',
    email: 'david.chen@pandaworks.com',
    role: 'Frontend Engineer',
    department: 'Engineering',
    timezone: 'Asia/Hong_Kong',
    avatarColor: 'oklch(0.65 0.15 240)',
  },
  {
    id: 'u8',
    name: 'Farah Hassan',
    email: 'farah.hassan@pandaworks.com',
    role: 'Product Designer',
    department: 'Design',
    timezone: 'Asia/Kuala_Lumpur',
    avatarColor: 'oklch(0.72 0.14 80)',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    key: 'PW-ATLAS',
    name: 'Atlas Platform Migration',
    description:
      'Migrate legacy monolith services to the new Atlas microservice platform. Includes auth, billing, and notification services.',
    status: 'active',
    priority: 'high',
    ownerId: 'u1',
    memberIds: ['u1', 'u3', 'u4', 'u7'],
    startDate: '2026-01-08',
    dueDate: '2026-06-30',
    progress: 64,
    budget: 180_000,
    tags: ['backend', 'infra'],
    createdAt: '2025-12-18',
  },
  {
    id: 'p2',
    key: 'PW-NOVA',
    name: 'Nova Design System',
    description:
      'Establish the Nova design system with tokens, primitives, and docs site. Roll out to all product surfaces.',
    status: 'active',
    priority: 'medium',
    ownerId: 'u2',
    memberIds: ['u2', 'u4', 'u8', 'u7'],
    startDate: '2026-02-01',
    dueDate: '2026-05-15',
    progress: 42,
    budget: 95_000,
    tags: ['design', 'frontend'],
    createdAt: '2026-01-22',
  },
  {
    id: 'p3',
    key: 'PW-PULSE',
    name: 'Pulse Analytics Rewrite',
    description:
      'Replace dated reporting stack with real-time analytics running on ClickHouse. Adds dashboards and anomaly alerts.',
    status: 'planning',
    priority: 'urgent',
    ownerId: 'u3',
    memberIds: ['u3', 'u5', 'u1'],
    startDate: '2026-05-01',
    dueDate: '2026-09-30',
    progress: 8,
    budget: 240_000,
    tags: ['data', 'backend'],
    createdAt: '2026-03-11',
  },
  {
    id: 'p4',
    key: 'PW-ORBIT',
    name: 'Orbit Customer Portal',
    description:
      'Self-serve portal for customers to manage subscriptions, seats, and invoices without contacting support.',
    status: 'on-hold',
    priority: 'low',
    ownerId: 'u6',
    memberIds: ['u6', 'u4', 'u7'],
    startDate: '2026-03-10',
    dueDate: '2026-08-01',
    progress: 22,
    budget: 60_000,
    tags: ['frontend', 'product'],
    createdAt: '2026-02-20',
  },
  {
    id: 'p5',
    key: 'PW-HORIZON',
    name: 'Horizon Mobile App',
    description:
      'Native companion app for frontline ops teams. Offline-first, barcode scanning, and shift handover workflows.',
    status: 'active',
    priority: 'high',
    ownerId: 'u5',
    memberIds: ['u5', 'u1', 'u8'],
    startDate: '2026-01-20',
    dueDate: '2026-07-31',
    progress: 55,
    budget: 220_000,
    tags: ['mobile', 'ops'],
    createdAt: '2025-12-03',
  },
  {
    id: 'p6',
    key: 'PW-ECHO',
    name: 'Echo Support Inbox',
    description:
      'Unified support inbox merging email, chat, and social. AI-assisted triage and canned response library.',
    status: 'completed',
    priority: 'medium',
    ownerId: 'u2',
    memberIds: ['u2', 'u6', 'u3'],
    startDate: '2025-08-01',
    dueDate: '2026-02-28',
    progress: 100,
    budget: 140_000,
    tags: ['product', 'ai'],
    createdAt: '2025-07-14',
  },
  {
    id: 'p7',
    key: 'PW-LUNA',
    name: 'Luna Billing Overhaul',
    description:
      'Rework the billing engine: usage-based tiers, prorations, tax compliance, and Stripe integration refactor.',
    status: 'active',
    priority: 'urgent',
    ownerId: 'u1',
    memberIds: ['u1', 'u3', 'u5'],
    startDate: '2026-02-15',
    dueDate: '2026-06-15',
    progress: 37,
    budget: 310_000,
    tags: ['backend', 'billing'],
    createdAt: '2026-01-30',
  },
  {
    id: 'p8',
    key: 'PW-QUILL',
    name: 'Quill Docs Site',
    description:
      'Public developer documentation site built on MDX with versioning, search, and interactive API explorer.',
    status: 'planning',
    priority: 'low',
    ownerId: 'u8',
    memberIds: ['u8', 'u2', 'u4'],
    startDate: '2026-05-15',
    dueDate: '2026-08-30',
    progress: 4,
    budget: 48_000,
    tags: ['docs', 'frontend'],
    createdAt: '2026-04-02',
  },
  {
    id: 'p9',
    key: 'PW-KOI',
    name: 'Koi Integrations Hub',
    description:
      'Central hub for third-party integrations: OAuth connection flows, webhook receivers, and event mapping.',
    status: 'active',
    priority: 'medium',
    ownerId: 'u3',
    memberIds: ['u3', 'u7', 'u5'],
    startDate: '2026-02-10',
    dueDate: '2026-07-10',
    progress: 48,
    budget: 130_000,
    tags: ['backend', 'integrations'],
    createdAt: '2026-01-12',
  },
];

export const TASKS: Task[] = [
  {
    id: 't1',
    projectId: 'p1',
    title: 'Carve auth service out of monolith',
    description: 'Spin up standalone auth microservice and switch traffic behind a feature flag.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'u3',
    dueDate: '2026-05-02',
    estimatedHours: 40,
    createdAt: '2026-02-18',
  },
  {
    id: 't2',
    projectId: 'p1',
    title: 'Billing service extraction',
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'u1',
    dueDate: '2026-05-20',
    estimatedHours: 60,
    createdAt: '2026-02-28',
  },
  {
    id: 't3',
    projectId: 'p1',
    title: 'Notification service extraction',
    status: 'review',
    priority: 'medium',
    assigneeId: 'u7',
    dueDate: '2026-04-22',
    estimatedHours: 32,
    createdAt: '2026-02-10',
  },
  {
    id: 't4',
    projectId: 'p1',
    title: 'Observability dashboards for Atlas',
    status: 'done',
    priority: 'medium',
    assigneeId: 'u4',
    dueDate: '2026-04-05',
    estimatedHours: 16,
    createdAt: '2026-03-01',
  },
  {
    id: 't5',
    projectId: 'p2',
    title: 'Token pipeline automation',
    status: 'done',
    priority: 'medium',
    assigneeId: 'u8',
    dueDate: '2026-03-20',
    estimatedHours: 24,
    createdAt: '2026-02-04',
  },
  {
    id: 't6',
    projectId: 'p2',
    title: 'Primitive library v1',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 'u4',
    dueDate: '2026-04-30',
    estimatedHours: 80,
    createdAt: '2026-02-14',
  },
  {
    id: 't7',
    projectId: 'p2',
    title: 'Docs site scaffold',
    status: 'in-progress',
    priority: 'medium',
    assigneeId: 'u7',
    dueDate: '2026-05-05',
    estimatedHours: 20,
    createdAt: '2026-03-04',
  },
  {
    id: 't8',
    projectId: 'p3',
    title: 'Spike: ClickHouse vs Druid',
    status: 'review',
    priority: 'high',
    assigneeId: 'u3',
    dueDate: '2026-04-25',
    estimatedHours: 12,
    createdAt: '2026-03-22',
  },
  {
    id: 't9',
    projectId: 'p3',
    title: 'Ingestion pipeline design doc',
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'u1',
    dueDate: '2026-05-10',
    estimatedHours: 16,
    createdAt: '2026-04-08',
  },
  {
    id: 't10',
    projectId: 'p5',
    title: 'Offline sync engine',
    status: 'in-progress',
    priority: 'urgent',
    assigneeId: 'u5',
    dueDate: '2026-05-18',
    estimatedHours: 72,
    createdAt: '2026-02-22',
  },
  {
    id: 't11',
    projectId: 'p5',
    title: 'Barcode scanner integration',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u8',
    dueDate: '2026-06-02',
    estimatedHours: 24,
    createdAt: '2026-03-12',
  },
  {
    id: 't12',
    projectId: 'p7',
    title: 'Usage meter for API plans',
    status: 'in-progress',
    priority: 'urgent',
    assigneeId: 'u3',
    dueDate: '2026-05-01',
    estimatedHours: 48,
    createdAt: '2026-03-03',
  },
  {
    id: 't13',
    projectId: 'p7',
    title: 'Proration calculator refactor',
    status: 'review',
    priority: 'high',
    assigneeId: 'u1',
    dueDate: '2026-04-28',
    estimatedHours: 28,
    createdAt: '2026-03-18',
  },
  {
    id: 't14',
    projectId: 'p9',
    title: 'Webhook receiver hardening',
    status: 'done',
    priority: 'medium',
    assigneeId: 'u7',
    dueDate: '2026-04-10',
    estimatedHours: 20,
    createdAt: '2026-02-19',
  },
  {
    id: 't15',
    projectId: 'p9',
    title: 'OAuth flow for Slack',
    status: 'in-progress',
    priority: 'medium',
    assigneeId: 'u5',
    dueDate: '2026-05-08',
    estimatedHours: 16,
    createdAt: '2026-03-27',
  },
];

export const ACTIVITY: ActivityEntry[] = [
  {
    id: 'a1',
    actorId: 'u3',
    projectId: 'p1',
    verb: 'moved',
    object: 'Carve auth service out of monolith to In Progress',
    at: '2026-04-21T08:12:00+08:00',
  },
  {
    id: 'a2',
    actorId: 'u4',
    projectId: 'p2',
    verb: 'commented on',
    object: 'Primitive library v1',
    at: '2026-04-21T07:40:00+08:00',
  },
  {
    id: 'a3',
    actorId: 'u1',
    projectId: 'p7',
    verb: 'raised priority on',
    object: 'Usage meter for API plans',
    at: '2026-04-20T17:55:00+08:00',
  },
  {
    id: 'a4',
    actorId: 'u2',
    projectId: 'p6',
    verb: 'closed',
    object: 'Echo Support Inbox',
    at: '2026-04-19T14:05:00+08:00',
  },
  {
    id: 'a5',
    actorId: 'u7',
    projectId: 'p1',
    verb: 'submitted',
    object: 'Notification service extraction for review',
    at: '2026-04-19T11:22:00+08:00',
  },
  {
    id: 'a6',
    actorId: 'u8',
    projectId: 'p2',
    verb: 'shipped',
    object: 'Token pipeline automation',
    at: '2026-04-18T16:10:00+08:00',
  },
  {
    id: 'a7',
    actorId: 'u5',
    projectId: 'p5',
    verb: 'created',
    object: 'Offline sync engine',
    at: '2026-04-18T09:30:00+08:00',
  },
];
